package View;

import Model.Student;
import Model.Professor;

import java.util.HashMap;
import java.util.Map;

/**
 *
 * @author chuongtruong
 */
public class FirstScreen extends javax.swing.JFrame {

    private Student[] student;
    private HashMap<Integer, Student> s = new HashMap<>();
    private HashMap<Integer, Professor> p = new HashMap<>();

    
    public FirstScreen(HashMap<Integer, Student> s, HashMap<Integer, Professor> p)
    {
        this.s = s;
        this.p = p;
        initComponents();
        System.out.println("Student hash from 1st screen" + s);
        System.out.println("professor hash from 1st screen" + p);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        professorButton = new javax.swing.JButton();
        studentButton = new javax.swing.JButton();
        TheGradeBookLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        professorButton.setText("Professor");
        professorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                professorButtonActionPerformed(evt);
            }
        });

        studentButton.setText("Student");
        studentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentButtonActionPerformed(evt);
            }
        });

        TheGradeBookLabel.setText("The Grade Book 1.0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(professorButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(studentButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(TheGradeBookLabel)))
                .addContainerGap(140, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(TheGradeBookLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(professorButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(studentButton)
                .addContainerGap(114, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void professorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_professorButtonActionPerformed
        this.dispose();
        new ProfessorLogin(s, p).setVisible(true);

    }//GEN-LAST:event_professorButtonActionPerformed

    private void studentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentButtonActionPerformed
        this.dispose();
        new SecondScreenStudent(s, p).setVisible(true);
    }//GEN-LAST:event_studentButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TheGradeBookLabel;
    private javax.swing.JButton professorButton;
    private javax.swing.JButton studentButton;
    // End of variables declaration//GEN-END:variables
}
