package View;

import Model.Professor;
import Model.Student;
import java.io.IOException;
import java.io.UncheckedIOException;
import java.io.Writer;
import java.nio.file.Files;
import javax.swing.table.DefaultTableModel;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author chuongtruong
 */
public class ThirdScreenProfessorB extends javax.swing.JFrame {

    private HashMap<Integer, Student> s = new HashMap<>();
    private HashMap<Integer, Professor> p = new HashMap<>();
    Professor professor;

    
    public ThirdScreenProfessorB(HashMap<Integer, Student> s, HashMap<Integer, Professor> p, Professor professor) {
        initComponents();

        this.s = s;
        this.p = p;
        this.professor = professor;
        
        System.out.println("Student hash from 3rd screen pro b" + s);
        System.out.println("professor hash from 3rd screen pro b " + p);

        DefaultTableModel model = (DefaultTableModel) tableView.getModel();
        
        s.values().forEach((student) -> {
            model.addRow(new Object[]{
                student.getStudentID(),
                student.getFirstName(),
                student.getLastName(),
                student.getQuiz(),
                student.getMidterm(),
                student.getFinalProject(),
                student.getAverage()
            });
            });
    }
                
                   


    
    private void addStudentToList()
    {
            DefaultTableModel model = (DefaultTableModel) tableView.getModel();
            s.values().forEach((student) -> {
            model.addRow(new Object[]{
                student.getStudentID(),
                student.getFirstName(),
                student.getLastName(),
                student.getQuiz(),
                student.getMidterm(),
                student.getFinalProject(),
            });
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu1 = new java.awt.PopupMenu();
        popupMenu2 = new java.awt.PopupMenu();
        popupMenu3 = new java.awt.PopupMenu();
        doneButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableView = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        popupMenu1.setLabel("popupMenu1");
        popupMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popupMenu1ActionPerformed(evt);
            }
        });

        popupMenu2.setLabel("popupMenu2");

        popupMenu3.setLabel("popupMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        doneButton.setText("<html>Done");
        doneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneButtonActionPerformed(evt);
            }
        });

        tableView.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "First Name", "Last Name", "Quiz", "Midterm", "Final Project", "GPA"
            }
        ));
        jScrollPane1.setViewportView(tableView);

        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(doneButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doneButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void doneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneButtonActionPerformed
        new SecondScreenProfessor(s,p, professor).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_doneButtonActionPerformed

    private void popupMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popupMenu1ActionPerformed
        // TODO add your handling code here:
        System.out.println(evt);
        
    }//GEN-LAST:event_popupMenu1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tableView.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) tableView.getModel();
        int studentID = Integer.parseInt(model.getValueAt(selectedRowIndex, 0).toString());
        
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog (null, "You are about to remove student " + studentID + " from the list.","Warning",dialogButton);
        if(dialogResult == JOptionPane.YES_OPTION){
            s.remove(studentID);
            System.out.println("Student ID" + studentID);
            model.removeRow(selectedRowIndex);
        }

//        try (Writer writer = Files.newBufferedWriter(./, ./)) {
//            s.forEach((key, value) -> {
//                try {
//                    writer.write(key + DATA_SEPARATOR + value + System.lineSeparator());
//                } catch (IOException ex) {
//                    throw new UncheckedIOException(ex);
//                }
//            });
//        } catch (UncheckedIOException ex) {
//            throw ex.getCause();
//        } catch (IOException ex) {
//            Logger.getLogger(ThirdScreenProfessorB.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton doneButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.PopupMenu popupMenu1;
    private java.awt.PopupMenu popupMenu2;
    private java.awt.PopupMenu popupMenu3;
    private javax.swing.JTable tableView;
    // End of variables declaration//GEN-END:variables
}
